CREATE NODE TABLE IF NOT EXISTS Copilot(name STRING, PRIMARY KEY(name))
CREATE NODE TABLE IF NOT EXISTS Developer(developer_id STRING, PRIMARY KEY(developer_id))
CREATE NODE TABLE IF NOT EXISTS Workspace(path STRING, PRIMARY KEY(path))
CREATE NODE TABLE IF NOT EXISTS Model(name STRING, PRIMARY KEY(name))
CREATE NODE TABLE IF NOT EXISTS Agent(name STRING, PRIMARY KEY(name))
CREATE NODE TABLE IF NOT EXISTS Session(session_key STRING, copilot STRING, model STRING, project_path STRING, started_at STRING, turn_count INT64, tool_call_count INT64, error_count INT64, PRIMARY KEY(session_key))
CREATE NODE TABLE IF NOT EXISTS Turn(turn_key STRING, sequence_num INT64, role STRING, is_sidechain BOOLEAN, slash_command STRING, PRIMARY KEY(turn_key))
CREATE NODE TABLE IF NOT EXISTS ToolInvocation(tool_key STRING, tool_name STRING, tool_name_raw STRING, is_error BOOLEAN, PRIMARY KEY(tool_key))
CREATE NODE TABLE IF NOT EXISTS FileNode(path STRING, language STRING, PRIMARY KEY(path))
CREATE NODE TABLE IF NOT EXISTS ErrorNode(error_key STRING, error_type STRING, tool_name STRING, PRIMARY KEY(error_key))
