#!/usr/bin/env bash
#
# generate-verification-draft.sh — deterministic draft generator for the
# requirement→verifier evidence graph (#193, Increment B of #190 §3).
#
# Emits specs/<feature-id>/verification.yaml with status: draft, one
# entry per FR-N in spec.md's `## Requirements` (both `- FR-N:` and
# `- **FR-N — ...**` conventions), computed statement_sha values, and
# placeholder verifiers that admission REJECTS — the author must review,
# map every requirement to a real executable verifier, and flip status
# to finalized. Admission (validate-spec.sh --unattended) validates the
# finalized artifact; it never authors it (#190 §3).
#
# Deterministic by construction: no model, no network, no timestamps —
# two runs over the same spec.md are byte-identical.
#
# Usage:
#   generate-verification-draft.sh <feature-id> [--force]
#
# --force overwrites an existing DRAFT. A finalized artifact is never
# overwritten (regenerate by deleting it deliberately — finalization is
# an author decision this tool must not undo).
#
# Exit codes: 0 written · 1 refused (exists) · 64 usage · 66 missing spec

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SPECS_DIR="${CCT_SPECS_DIR:-$REPO_DIR/specs}"

# shellcheck source=lib/verification-common.sh
source "$SCRIPT_DIR/lib/verification-common.sh"

FEATURE_ID=""
FORCE=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force) FORCE=true; shift ;;
        -*) echo "usage: $0 <feature-id> [--force]" >&2; exit 64 ;;
        *)  FEATURE_ID="$1"; shift ;;
    esac
done
[[ -n "$FEATURE_ID" ]] || { echo "usage: $0 <feature-id> [--force]" >&2; exit 64; }

SPEC="$SPECS_DIR/$FEATURE_ID/spec.md"
OUT="$SPECS_DIR/$FEATURE_ID/verification.yaml"
[[ -f "$SPEC" ]] || { echo "error: $SPEC not found" >&2; exit 66; }

if [[ -f "$OUT" ]]; then
    existing_status="$(vc_parse_artifact "$OUT" | awk -F'\t' '$1 == "STATUS" { print $2; exit }')"
    if [[ "$existing_status" == "finalized" ]]; then
        echo "refusing: $OUT is finalized — finalization is an author decision" >&2
        echo "this tool must not undo. Delete the file deliberately to regenerate." >&2
        exit 1
    fi
    if [[ "$FORCE" != "true" ]]; then
        echo "refusing: $OUT exists (status: ${existing_status:-unknown}). Use --force to regenerate the draft." >&2
        exit 1
    fi
fi

FRS="$(vc_extract_frs "$SPEC")"
if [[ -z "$FRS" ]]; then
    echo "error: no FR-N requirements found in $SPEC (## Requirements section)" >&2
    exit 66
fi

# yaml_quote <s> — double-quoted YAML scalar (escape backslash + quote).
yaml_quote() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '"%s"' "$s"
}

{
    echo "# verification.yaml — requirement→verifier evidence graph (#190 §3)."
    echo "# Generated by scripts/generate-verification-draft.sh — review each"
    echo "# entry, replace every placeholder with a real executable verifier,"
    echo "# then set status: finalized. spec.md is the only authoritative"
    echo "# source of requirement text; statement below is display-only and"
    echo "# statement_sha binds it (admission recomputes and fails on drift)."
    echo "# Contract: shared/schemas/verification.schema.json"
    echo "status: draft"
    echo "feature_id: $FEATURE_ID"
    echo ""
    while IFS=$'\t' read -r fr stmt; do
        echo "$fr:"
        echo "  statement: $(yaml_quote "$stmt")"
        echo "  statement_sha: \"$(vc_fr_sha "$fr" "$stmt")\""
        echo "  verifiers:"
        echo "    - kind: deterministic"
        echo "      test: \"TODO — map $fr to an executable verifier (path or command)\""
    done <<< "$FRS"
} > "$OUT"

count="$(printf '%s\n' "$FRS" | wc -l | tr -d ' ')"
echo "draft written: $OUT ($count requirement(s)) — review, map verifiers, set status: finalized"
