#!/usr/bin/env bash
# setup-reviewer.sh — Install an independent-reviewer configuration for a
# copilot into a target project.
#
# Installs, per copilot, the pieces that make that copilot act as an
# independent code reviewer for the project:
#   docs/CODE_REVIEW.md       full review workflow (from shared/review/)
#   <instruction file>        a short marker-guarded "Code Review Rules"
#                             loader section directing the copilot to read it
#
# Supported copilots (dispatch table below — add new tools there):
#   --codex     loader goes into the project's root AGENTS.md
#
# Usage:
#   ./scripts/setup-reviewer.sh --codex [PROJECT_DIR]
#   ./scripts/setup-reviewer.sh --codex --uninstall [PROJECT_DIR]
#   ./scripts/setup-reviewer.sh --list
#
# PROJECT_DIR defaults to the current directory. Re-running refreshes the
# managed block and document in place (idempotent). Files this script did not
# install are never overwritten: a foreign docs/CODE_REVIEW.md is refused, and
# an instruction file generated by code-copilot-team (generate.sh header) is
# skipped — that file receives the loader at the generator layer instead, so
# regeneration cannot erase it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$SCRIPT_DIR/.."
REVIEW_SRC="$REPO_DIR/shared/review/CODE_REVIEW.md"
LOADER_SRC="$REPO_DIR/shared/review/reviewer-loader.md"

DOC_MARK="<!-- CCT-REVIEWER-MANAGED: installed by setup-reviewer.sh; source: shared/review/CODE_REVIEW.md -->"
begin_mark() { echo "<!-- BEGIN CCT-REVIEWER ($1) — managed by setup-reviewer.sh; edits inside this block are overwritten -->"; }
end_mark()   { echo "<!-- END CCT-REVIEWER ($1) -->"; }

err() { echo "[setup-reviewer] ERROR: $*" >&2; }

# ── Shared mechanics (tool-agnostic) ────────────────────────

doc_is_ours() { [[ -f "$1" ]] && head -1 "$1" | grep -qF "CCT-REVIEWER-MANAGED"; }

install_doc() {
  local project="$1"
  local target="$project/docs/CODE_REVIEW.md"
  if [[ -f "$target" ]] && ! doc_is_ours "$target"; then
    err "$target exists and was not installed by this script. Refusing to overwrite."
    err "Move it aside or merge shared/review/CODE_REVIEW.md into it manually."
    return 1
  fi
  mkdir -p "$project/docs"
  { echo "$DOC_MARK"; cat "$REVIEW_SRC"; } > "$target"
  echo "  Installed $target"
}

uninstall_doc() {
  local target="$1/docs/CODE_REVIEW.md"
  if doc_is_ours "$target"; then
    rm -f "$target"
    echo "  Removed $target"
  elif [[ -f "$target" ]]; then
    echo "  [SKIP] $target is not managed by this script — left in place"
  fi
}

# Remove the managed block (if any), then append a fresh one. The block sits
# at the end of the file after a refresh; content outside the markers is
# never touched.
upsert_loader_block() {
  local file="$1" tool="$2"
  local b e tmp
  b="$(begin_mark "$tool")"
  e="$(end_mark "$tool")"
  tmp="${file}.cct-reviewer.tmp"
  if [[ -f "$file" ]]; then
    awk -v b="$b" -v e="$e" '$0==b{skip=1; next} $0==e{skip=0; next} !skip{print}' "$file" > "$tmp"
  else
    printf '# Agent Instructions\n' > "$tmp"
  fi
  # Trim trailing blank lines so re-runs are byte-identical.
  while [[ "$(tail -1 "$tmp" 2>/dev/null)" == "" && -s "$tmp" ]]; do
    sed -i.bak -e '$d' "$tmp" && rm -f "${tmp}.bak"
  done
  {
    echo ""
    echo "$b"
    echo ""
    cat "$LOADER_SRC"
    echo ""
    echo "$e"
  } >> "$tmp"
  mv "$tmp" "$file"
  echo "  Installed Code Review Rules loader in $file"
}

remove_loader_block() {
  local file="$1" tool="$2"
  [[ -f "$file" ]] || return 0
  local b e tmp
  b="$(begin_mark "$tool")"
  e="$(end_mark "$tool")"
  grep -qF "$b" "$file" || return 0
  tmp="${file}.cct-reviewer.tmp"
  awk -v b="$b" -v e="$e" '$0==b{skip=1; next} $0==e{skip=0; next} !skip{print}' "$file" > "$tmp"
  while [[ "$(tail -1 "$tmp" 2>/dev/null)" == "" && -s "$tmp" ]]; do
    sed -i.bak -e '$d' "$tmp" && rm -f "${tmp}.bak"
  done
  mv "$tmp" "$file"
  echo "  Removed Code Review Rules loader from $file"
}

instruction_file_is_generated() {
  [[ -f "$1" ]] && head -5 "$1" | grep -q "Auto-generated" && head -5 "$1" | grep -q "generate.sh"
}

# ── Per-copilot installers (the dispatch surface) ───────────

install_codex() {
  local project="$1"
  local agents="$project/AGENTS.md"
  install_doc "$project" || return 1
  if instruction_file_is_generated "$agents"; then
    echo "  [SKIP] $agents is generated by code-copilot-team — the loader ships"
    echo "         at the generator layer (scripts/generate.sh); run"
    echo "         './scripts/generate.sh' (or the adapter's setup.sh --sync)."
    return 0
  fi
  upsert_loader_block "$agents" "codex"
}

uninstall_codex() {
  local project="$1"
  remove_loader_block "$project/AGENTS.md" "codex"
  uninstall_doc "$project"
}

SUPPORTED_TOOLS="codex"

# ── CLI ─────────────────────────────────────────────────────

TOOL=""
UNINSTALL=false
PROJECT_DIR=""
for arg in "$@"; do
  case "$arg" in
    --codex)     TOOL="codex" ;;
    --uninstall) UNINSTALL=true ;;
    --list)      echo "Supported reviewer copilots: $SUPPORTED_TOOLS"; exit 0 ;;
    --help|-h)   sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --*)         err "unknown copilot or flag: $arg (supported: $SUPPORTED_TOOLS)"; exit 64 ;;
    *)           PROJECT_DIR="$arg" ;;
  esac
done

if [[ -z "$TOOL" ]]; then
  err "no copilot selected (supported: $SUPPORTED_TOOLS). Usage: setup-reviewer.sh --codex [PROJECT_DIR]"
  exit 64
fi

PROJECT_DIR="${PROJECT_DIR:-$PWD}"
if [[ ! -d "$PROJECT_DIR" ]]; then
  err "project directory not found: $PROJECT_DIR"
  exit 66
fi
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"

if $UNINSTALL; then
  echo "=== Removing $TOOL reviewer configuration from $PROJECT_DIR ==="
  "uninstall_$TOOL" "$PROJECT_DIR"
  echo "=== Done ==="
else
  echo "=== Installing $TOOL reviewer configuration into $PROJECT_DIR ==="
  "install_$TOOL" "$PROJECT_DIR"
  echo ""
  echo "Next: fill in the Project Configuration placeholders in"
  echo "  $PROJECT_DIR/docs/CODE_REVIEW.md"
  echo "then start a fresh $TOOL session so the instruction chain reloads."
  echo "=== Done ==="
fi
